# Generated by Django 4.0.4 on 2022-05-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField(default=None)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('metrs', models.FloatField(default=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='olx_bot_app.city')),
            ],
        ),
    ]
